### ISSUE TITLE
how do you install on quest

### ISSUE THREAD

**Issue by Cxsmo-ai** [ChisdealHDYT/BeatSaber-BOT-Quest-PC#1]
how do you install on quest

**Comment by Cxsmo-ai** [comment]
how do you install on quest

**Comment by NekoSuneVR** [comment]
all info in readme, need get Sidequest and follow says

after do that need plug in Cabe to Pc let BOt detect Quest 1/2 see its IP and be automatic saved for wirelessly

all this needs have Pc or laptop do it

**Comment by NekoSuneVR** [comment]
i closing this ticket, hasnt been active less then 5 minutes.
